### ISSUE TITLE
Cants grab novels from https://chrysanthemumgarden.com

### ISSUE THREAD

**Issue by Tetdesu** [mHaisham/novelsave#23]
I tried to grab a novel from https://chrysanthemumgarden.com
But it wont get the novel

It is saying the following error (on the ss)

![IMG_20210402_000736.jpg](https://user-images.githubusercontent.com/75838212/113322869-cdd23a80-9347-11eb-8720-d5bfb34e146d.jpg)

**Comment by mHaisham** [comment]
Install the latest version from the repository

```bash
pip install git+https://github.com/mHaisham/novelsave.git --no-deps --force
```

`--no-deps` to not install dependencies as they havent changed from previous

`--force` to uninstall existing and install anew

PS. sorry for the late reply

**Comment by Tetdesu** [comment]
It worked. 😁
Thanks
