### ISSUE TITLE
Missing paragraph

### ISSUE THREAD

**Issue by 1jamie7** [mHaisham/novelsave#31]
Hi! There seems a missing paragraph to the epub I made from https://chrysanthemumgarden.com/ site.

from the site

![20210505_165611.jpg](https://user-images.githubusercontent.com/74856769/117118217-6001a000-ad45-11eb-9088-da809dd2009e.jpg)

from the epub I made

![20210505_165553.jpg](https://user-images.githubusercontent.com/74856769/117118261-6d1e8f00-ad45-11eb-9aa0-3d6c6dac1a5b.jpg)

**Comment by mHaisham** [comment]
Could you post the link to the chapter.

**Comment by 1jamie7** [comment]
https://chrysanthemumgarden.com/novel-tl/pubg/pubg-28/

**Comment by mHaisham** [comment]
The bug was cause by the blacklisted pattern `^[\W\D]*(volume|chapter)[\W\D]+\d+[\W\D]*$` matching the paragraph.

```bash
>>> import re
>>> re.match(r'^[\W\D]*(volume|chapter)[\W\D]+\d+[\W\D]*$', 'He clicked to sort the listings by the highest sale volume, and all of them were cheap goods under 30 yuan. The store had countless poor reviews—after all, you get what you paid for—and these were all just bought for the purpose of video chatting with family members, and etc. No matter how poor the quality was, as long as the person could be seen, it was fine.')

<re.Match object; span=(0, 362), match='He clicked to sort the listings by the highest sa>
```

Telling it was unexpected would be an understatement. good job catching it.
