### ISSUE TITLE
Can not get novels from dummynovels.com

### ISSUE THREAD

**Issue by 1jamie7** [mHaisham/novelsave#34]
Hi! Seems like dummynovels change something on their site? I can't get novels from there anymore. It looks like this
![Screenshot_20210603-172703_Termux.jpg](https://user-images.githubusercontent.com/74856769/120623179-15815980-c492-11eb-86b7-2b375403c806.jpg)

By the way, I'm using termux 😁

**Comment by mHaisham** [comment]
I'll look into it asap

**Comment by mHaisham** [comment]
now you'll just need to update novelsave

```
pip install git+https://github.com/mHaisham/novelsave.git --no-deps --force
```
