### ISSUE TITLE
[Bug] Unable to detect pending chapter properly

### ISSUE THREAD

**Issue by Addicted5** [mHaisham/novelsave#6]
After last update, new chapters are not detecting properly & it's downloading all chapters from starting.
Then epub created also contains multiple no of same chapter(3 copy of chapter is there if i ran novel save 3 times, 4 if i ran it 4 times etc)

**Comment by mHaisham** [comment]
The last update was a breaking update, the previous database wont work.. it doesnt have backward compatibility.

Indeed, i need to distinguish the latest update databases from previous ones.

**Comment by Addicted5** [comment]
Ohh, no i actually used a different directory, previous database deleted anyway.

**Comment by mHaisham** [comment]
Thats weird.. i'll it check it

**Comment by mHaisham** [comment]
If you could provide the source, it would be wonderful

**Comment by Addicted5** [comment]
https://www.wuxiaworld.co/Mages-Are-Too-OP/ or https://www.wuxiaworld.co/Supreme-Magus/

**Comment by mHaisham** [comment]
Fixed 4fbe02c5744ab4c7b505a3a88aaef8cfac34920c
